### ISSUE TITLE
Best Practice / Docs clarification on `token_reviewer_jwt`

### ISSUE THREAD

**Issue by gavinelder** [hashicorp/vault-plugin-auth-kubernetes#106]
👋  First of all, thank you for this amazing plugin. 

The following is a clarification / potential best practice docs contribution around the `token_reviewer_jwt` which I am happy to do but I just wanted to flesh out the thoughts and views of this community before raising any PRs.

I also see a number of issues that indicate some confusion around authentication methods https://github.com/hashicorp/vault-plugin-auth-kubernetes/issues/95#issue-667608857  

# Current Mental Model of Auth methods for this plugin.

The following is my current mental model of these plugins authentication methods and approaches please correct me if anything is incorrect or there are additional risks I have not considered in relation to the delegation of `system:auth-delegator` 

For example, I have not fully considered the privilege of a Service Account or the risks associated with account enumeration or other lateral movement paths. 

## Background

In late 2017 #6 was raised to allow the use of an optional dedicated vault account to be used by vault to authenticate this service account would have permission to use the `TokenReview API` 

The `TokenReview API` is an API call to see if a JWT Token received as part of the authentication request to the Vault instance is still valid and has not been revoked before issuing a vault session token. 

## Possible approaches 

When the use of a vault agent in a remote cluster is removed I see three valid approaches one can take to administering and granting Authorization against a remote vault instance. 

### Using a shared service account

A shared service account can be used to validate the JWT token is indeed valid at the time of the request, this service account can be used 

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: default
```

- Pro
    - This reduces the need to grant `TokenReview API` permissions to Kubernetes services
- Con
    - This shared service account can be considered somewhat sensitive and customers who look to define their vault configuration as code such as with https://github.com/hashicorp/terraform-provider-vault would have to store this credential either within a remote backend or worse as a raw string in code so this approach is probably not advisable to them. 
    - As a vault administrator it is not possible to determine if the `token_reviewer_jwt` is set or to what value as such it is somewhat magical this is listed in the issue https://github.com/hashicorp/vault-plugin-auth-kubernetes/issues/68  

### CRD to grant all service accounts access to the `TokenReview API`

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
```

- Pro
    - This reduces the need to grant `TokenReview API` permissions 
- Con
    - This results in a higher privilege to all Kubernetes 

### CRD to grant named service accounts access to the `TokenReview API`

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: $SERVICE_NAME
    namespace: $NAMESPACE
```

- Pro
    -  Implements the least privilege per service.
- Con
    - Administrative overhead.
    - Additional complexity.
