### ISSUE TITLE
Vault should support reloading service account token from disk

### ISSUE THREAD

**Issue by tsaarni** [hashicorp/vault-plugin-auth-kubernetes#121]
I believe I've found some issues with the current service account token handling.

**Background**

**(1)** Kubernetes issues service account tokens that expire. Beginning from Kubernetes 1.21 the default expiration time for the token is 1 year but it can be configured down to 1 hour.

**(2)** Kubernetes associates issued tokens with particular pod via claim `\"kubernetes.io\".pod.name`.

Example id token from Kubernetes 1.22.0

```yaml
{'aud': ['https://kubernetes.default.svc.cluster.local'],
 'exp': 1634052974,
 'iat': 1634049374,
 'iss': 'https://kubernetes.default.svc.cluster.local',
 'kubernetes.io': {'namespace': 'default',
                   'pod': {'name': 'myapp-674f595ff9-q6w4q',
                           'uid': '2ac5b2e8-f74d-4fef-b410-cc5bebf574b1'},
                   'serviceaccount': {'name': 'my-service-account',
                                      'uid': '2fa34b84-7014-4860-a84f-93707230c0cd'}},
 'nbf': 1634049374,
 'sub': 'system:serviceaccount:default:my-service-account'}
```

If the token is used after pod has been deleted, `401 Unauthorized` response will be returned and following error is logged by the API server:

```
E1012 14:37:47.799799       1 authentication.go:63] "Unable to authenticate the request" err="[invalid bearer token, Token has been invalidated]"
```

The claim is checked by the code [here](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/serviceaccount/claims.go#L169-L175).

**Problem description**

Kubernetes Auth Backend seems to store the token persistently when auth method is configured by POSTing to `/auth/kubernetes/config`.

The stored token will stop working when:

1. Token expires within one year (or sooner if default has been changed).
2. When the pod (where the token originates from) is deleted.

**Proposed fix**

Kubernetes Auth Backend could use similar approach as other Kubernetes clients do:

- Load token from disk and do not store it persistently.
- Reload token when it is renewed.
