### ISSUE TITLE
Not a compact JWS error

### ISSUE THREAD

**Issue by baptiste-bonnaudet** [hashicorp/vault-plugin-auth-kubernetes#25]
Hey I have an issue delegating authentication to k8s, I configured my backend as follow:

#### K8s CA cert 
/tmp/example.crt contains the K8s cert to authenticate to the API, from my ~/.kube/config

#### tokenreview JWT
ACCOUNT_TOKEN=$(kubectl -n default get secret `kubectl -n default get serviceaccount vault-tokenreview -o jsonpath='{.secrets[0].name}'` -o jsonpath='{.data.token}' | base64 --decode)

```
vault write -f auth/kube-example/config kubernetes_host=$GKE_URL kubernetes_ca_cert=@/tmp/example.crt token_reviewer_jwt=$ACCOUNT_TOKEN

vault write auth/kube-example/role/myapplication \
    bound_service_account_names=myapplication \
    bound_service_account_namespaces=myapplication \
    policies=myapplication \
    ttl=48h \
    max_ttl=48h
```

Created before with the config:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-tokenreview
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: vault-tokenreview-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-tokenreview
  namespace: default
```

#### Pod SA
```
curl --request POST --data '{"jwt": "$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)", "role": "myapplication"}' https://vault.example.com/v1/auth/kube-example/login
{"errors":["not a compact JWS"]}
```

I tried playing with both jwts and base64 encoding but no luck and this is driving me crazy. Am I missing something?
