### ISSUE TITLE
Add custom metadata to Vault from ServiceAccount annotations

### ISSUE THREAD

**Issue by mrknmc** [hashicorp/vault-plugin-auth-kubernetes#85]
We would like to create policy rules that use custom entity/alias metadata and have this metadata be supplied from Kubernetes annotations on the ServiceAccount.

The way I envision this working is, if you have a ServiceAccount with annotations such as:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-account
  namespace: default
  annotations:
    # could have different form
    vault.hashicorp.com/auth-metadata/metadata-key: example-value
```

Then the auth plugin adds following metadata to the entity/alias:

```
metadata-key: example-value
```

We could then create a templated policy document (in Terraform) such as:

```
data "vault_policy_document" "tokens_write_document" {
  path         = "root/{{identity.entity.aliases.<mount-accessor>.metadata.<metadata-key>}}/*"
  capabilities = ["write", "list", "read"]
}
```

And with this policy in place, the ServiceAccount would have access to any secret under:

```
/root/example-value/*
```

Currently, we would have to manually edit entity/alias metadata to achieve this at which point we might as well create per-service-account policies which we would really like to avoid doing.

What are your thoughts on this? I would gladly submit a PR.

I'm thinking what would be necessary is to make an extra request to get the annotations for a given service account, parse them, and pass them to Vault in this code block: https://github.com/hashicorp/vault-plugin-auth-kubernetes/blob/master/path_login.go#L112-L133. Extra RBAC permissions would be required for the JWT reviewer service account too.
