### ISSUE TITLE
permission denied while creating external secrets

### ISSUE THREAD

**Issue by nitin-wise** [hashicorp/vault-plugin-auth-kubernetes#92]
Hi, I am trying to use the vault kubernetes auth with k8s external secrets provided by Godaddy https://github.com/godaddy/kubernetes-external-secrets#hashicorp-vault. 
Note: the external secrets is configured in vault namespace.
My vault endpoint is configured in external secrets env var $VAULT_ADDR . 
Created new secret in vault using vault token login from my machine in kv engine. 
```vault kv put secret/dev/rds @pass.json```  
Enabled auth using 
```vault auth enable -path=k8s-cluster kubernetes```  
Configured auth using 
```
k8s_host="$(kubectl config view --minify | grep server | cut -f 2- -d ":" | tr -d " ")"
k8s_cacert="$(kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.certificate-authority-data}' | base64 --decode)"
secret_name="$(kubectl get serviceaccount vault-auth -n vault -o go-template='{{ (index .secrets 0).name }}')"
tr_account_token="$(kubectl get secret ${secret_name} -n vault -o go-template='{{ .data.token }}' | base64 --decode)"
```
```
vault write auth/k8s-cluster/config token_reviewer_jwt="${tr_account_token}" kubernetes_host="${k8s_host}" kubernetes_ca_cert="${k8s_cacert}"
```
Policy to read all secrets in kv, 
```
vault policy write k8s-policy-read - <<EOF
path "secret/*" {
    capabilities = ["read", "list"]
}
EOF
```
Role to allow above policy
```
vault write auth/k8s-cluster/role/sbx  \  
    bound_service_account_names=vault-auth   \
    bound_service_account_namespaces=vault   \
    policies=k8s-policy-read \
    ttl=1h
```

The external secrets manifest creates a service account `vault-auth` in vault namespace. 
After creating the external secret to fetch above secret as below, I get `permission denied`
```
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: secret-rds
  namespace: vault
spec:
  backendType: vault
  # Your authentication mount point, e.g. "kubernetes"
  vaultMountPoint: k8s-cluster
  # The vault role that will be used to fetch the secrets
  # This role will need to be bound to kubernetes-external-secret's ServiceAccount; see Vault's documentation:
  # https://www.vaultproject.io/docs/auth/kubernetes.html
  vaultRole: sbx
  data:
  - name: pass
    # The full path of the secret to read, as in `vault read secret/data/hello-service/credentials`
    key: secret/dev/rds
    property: pass
  # Vault values are matched individually. If you have several keys in your Vault secret, you will need to add them all separately
  - name: user
    key: secret/dev/rds
    property: user

```

This should ideally create a secret, but gives below error in secret event: 
```
Status:               ERROR, permission denied
```

The external secret controller gives similar error. :
```
{"level":50,"time":1591282202905,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-fbdf84d6f-d65st","response":{"statusCode":403,"body":{"errors":["permission denied"]}},"stack":"Error: permission denied\n    at handleVaultResponse (/app/node_modules/node-vault/src/index.js:49:21)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async VaultBackend._get (/app/lib/backends/vault-backend.js:42:21)\n    at async /app/lib/backends/kv-backend.js:29:31\n    at async Promise.all (index 0)\n    at async Promise.all (index 1)\n    at async VaultBackend.getSecretManifestData (/app/lib/backends/kv-backend.js:116:42)\n    at async Poller._createSecretManifest (/app/lib/poller.js:88:18)\n    at async Poller._upsertKubernetesSecret (/app/lib/poller.js:152:28)","type":"Error","msg":"failure while polling the secret vault/secret-rds"}
{"level":30,"time":1591282202919,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-fbdf84d6f-d65st","msg":"stopping poller for vault/secret-rds"}
```

This purely shows authorization error, but as the policies and roles are mapped properly, the permission denied must not be coming. Not sure if I am missing anything, any help or discussion will be appreciated. Thanks in advance.

**Comment by rchenzheng** [comment]
I seem to be having the same issue but everything points to kubernetes auth not being configure appropriately 
https://www.vaultproject.io/docs/auth/kubernetes

**Comment by ricanol** [comment]
In case anyone has the same problem!

In my case I enabled the option: "Disable use of local CA and service account JWT"
![image](https://user-images.githubusercontent.com/78149308/160682155-319d268f-e10c-48cd-bc1c-ea421e586be3.png)

**Comment by tomhjp** [comment]
Hi all, sorry to have left this without response for so long. I imagine you're no longer having the same issues, but in case it's helpful for others, I've taken a look below. In general, I would recommend the Vault section of our [discuss forum](https://discuss.hashicorp.com/c/vault/30) for debugging help like this.

As @ricanol has found, I would suggest the most likely failure point is on authentication. There are a number of reasons k8s auth may return 403, and judging from your policy it shouldn't be possible to get a 403 from reading the paths you've specified. However, be careful with the path for KV. It looks like you're using the default `secret` mount, which defaults to being KV v2, and that has a `data` component in the path: https://www.vaultproject.io/api-docs/secret/kv/kv-v2#read-secret-version. So e.g. the external secret spec should probably be like this:

```yaml
  - name: user
    key: secret/data/dev/rds
    property: user
```

As for the 403 itself, I can't be sure but I think this probably down to this part:

```bash
vault write auth/k8s-cluster/role/sbx  \  
    bound_service_account_names=vault-auth   \
    bound_service_account_namespaces=vault   \
    policies=k8s-policy-read \
    ttl=1h
```

Specifically, the `bound_service_account` specifies which service accounts can use this role to log in. As you haven't specified `serviceAccountRef` or `secretRef` in the CRD, it will be using the operator's own service account to auth with Vault. So it would have to be running as the `vault-auth` service account to be allowed to log in. Further documentation on that here: https://external-secrets.io/v0.4.4/provider-hashicorp-vault/#kubernetes-authentication.
